Update swift package manager with platform
andreamazz/AMPopTip pull request #227
Opened 2021-09-24 10:23 UTC by minenordlicht

Fix Archive build w/ SwiftUI dependency fails in Xcode 13 by suggest from apple 
https://developer.apple.com/forums//thread/690405?answerId=688640022&replyId=688640022

2021-10-01 07:20 UTC, andreamazz requested changes

2021-10-01 07:20 UTC, andreamazz commented on Package.swift
> +  platforms: [.iOS(.v12), .macOS(.v10_14), .tvOS(.v12), .watchOS(.v5)],
We only support iOS, 11 up, not the other platforms

2021-12-31 04:21 UTC, codywalker77 approved these changes

2022-01-08 11:49 UTC, merged

2022-01-08 11:49 UTC, andreamazz commented
Guess I'll change it myself